appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: Owf1Yy4HHEYuNao/l/2uIWnYXDLFJvXWCmuCOymJaRbXVFlV7XgjDeZJtqObA9MILULvoHyEinEER3BjSj7wNjg0zFcORVFgmmgr7eOU8Wl3VTOThKtWV30HSoJFoytfztENUZbJR/z60PVxKnXaeQfiHxVaEzryBb4cQnHXM5tBF42mqVQaI+GcLoeTvp2rPJjESkW9QzmnhvRXn8H4hk2FC1BsGsTWfMhXmMJA4haiEx0SHpw57+6yE1eoc2b/ckQcmdDDLDFTdM/ClmcTqVvKpWIXuEKLkp2ZJe5GcgI3IEi7Qp6TZwpr1ST3RRp85IH7e9q/8LZIjMJsT15/D4YEwLq2M5BmevtGvMOcF7g/ukJOjPXDdNH1J+L72KHzz89+SphpfxCLSCZeRGfhG0h0AwFM0inD/JV/TnwdeBy/bkeNpAVF4nh+5Ab6jo4SQPiwe02ZVd0SLsT+0SUcKKWjZtQ4XkCrfYhFt+aS+RTB4ZucOPTrOHZNdRJVG68rS/gpSYoxfwgJBJBTxfUzs4soYVQuZZR2E1M55dFsE4ZUPTWSuUVLHmbV1oFXJ5jzFX5eWqEtf6nvoqmA7mVFW+9CBk1ZOm+Ixq4Ai6bpbiVtRChH7Ux2OHOi/OgfEUIqrVWr2wKNyDX6Yw9pO9j8buSsHWBSns4jkU4sGD1sARQ=}
